
# AWS Region
region: eu-west-1

# Project Name
project: cds-57

# Stacks
stacks:
  app:
    source: /Users/shauncoralogix/Projects/cloudformation-corlaogix-aws/opentelemetry/ecs-ec2/template.yaml
    parameters:
      # - Image: 'arn:aws:ecr:eu-west-1:035955823196:repository/otel-cds-68'
      - CoralogixRegion: Europe
      - ApplicationName: cds-141
      - SubsystemName: ecs
      - PrivateKey: ba29cda0-4185-ade5-dd43-964b8b529c57
      - ClusterName: cds-68


